### ISSUE TITLE
PEP8 and CI

### ISSUE THREAD

**Issue by s-celles** [okfn/datapackage-validate-py#10]
Adding PEP8 conformance tests at CI build might be a good idea.

We just need to add

```
script:
    - flake8 --ignore E501 datapackage_validate tests *.py
```

to `.travis.yml`

and `flake8` might be add to `dev-requirements.py`

see also https://github.com/okfn/datapackage-validate-py/issues/9

**Comment by pwalsh** [comment]
Thanks. We are using `pylint` with this [config](https://github.com/okfn/oki-py/blob/master/pylintrc). We are going to merge this code directly into https://github.com/datapackages/datapackage-py for the V1 release, and linting etc will be taken care of there.

**Comment by s-celles** [comment]
ok thanks
