### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-validate-py#4]
There are two issues with how we handle errors IMHO: 1) the use of errors as strings; 2) returning the errors, instead of raising them.

The first issue is a problem because it requires the users of this code, if they want to analyze what errors happened, to check the strings' content. This leads to a high coupling between their code and this library (they'll break if we change the strings, for example). So, instead of bare strings, we should use Exceptions.

The second issue is less important, as it's mostly about API design. I think the reasoning behind it was to send the user every error with their datapackage/schema. This would allow her to fix all (most) errors at once, instead of fixing one, trying again, fixing another, trying again, etc...

That being the case, I think a better solution would be to have a `DataPackageValidateException` with a `.errors` property, holding every error that happened during the validation. This way, the usage changes from:

``` python
import datapackage_validate

valid, errors = datapackage_validate.validate(datapackage, schema)
if not valid:
    # Do whatever you want with the errors
```

to:

``` python
import datapackage_validate

try:
    datapackage_validate.validate(datapackage, schema)
except datapackage_validate.exceptions.DataPackageValidateException as e:
    e.errors  # Do whatever you want with the errors
```

Which seems to me a more common pattern in Python.

**Comment by pwalsh** [comment]
Yes. Also, for reference see a similar implementation https://github.com/okfn/jsontableschema-py/blob/master/jsontableschema/validate.py

**Comment by vitorbaptista** [comment]
Great example, @pwalsh :+1:

**Comment by vitorbaptista** [comment]
The remaining issue here is to use something like `six.raise_from` to avoid loosing the traceback of the Exceptions after wrapping them.

http://python-future.org/compatible_idioms.html#raising-exceptions

**Comment by brew** [comment]
@joetsoi used `future.raise_with_traceback` in jsontableschema-py (https://github.com/okfn/jsontableschema-py/blob/812782fceaeb81b21e3b4c27918ac128aae68e46/jsontableschema/types.py#L22)

http://python-future.org/compatible_idioms.html#raising-exceptions

**Comment by vitorbaptista** [comment]
I'm not sure if it's better to `raise_from`, keeping the original exception, or simply `raise_with_traceback`. I've been using `raise_from`, because I guess it helps debugging the issues, but maybe `raise_with_traceback` is better to encapsulate the packages dependencies.

I was looking for something to help me decide between `six` and `future`, but couldn't find anything. Even the `future` FAQ isn't clear on which one is better (http://python-future.org/faq.html#what-is-the-relationship-between-future-and-six). It seems there's no clear winner yet.

I went with `six` because it's smaller, older, and more common (5.5 million of downloads in the last month, against future's 100k). Any of those will be fine, though.

**Comment by brew** [comment]
Ah - didn't realise you were already using six. We may want to standardise to it in jsontableschema-py too.

**Comment by vitorbaptista** [comment]
This repository is now deprecated, with all development moving to https://github.com/datapackages/datapackage-py/
