### ISSUE TITLE
Import code from datapackage-py's Schema class

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-validate-py#6]
For more information, check https://github.com/okfn/datapackage-py/issues/22

**Comment by vitorbaptista** [comment]
The code is still more complicated than it should be, specially the number of different exceptions thrown, but the behaviour is the same as before, except for the exception type raised when an invalid schema ID was passed.

**Comment by pwalsh** [comment]
@vitorbaptista can you simplify it then? This package is pretty much the reference implementation for other languages to do validation - if something can be simplified, please outline it here and let's see if we do it.

**Comment by vitorbaptista** [comment]
This repository is now deprecated, with all development moving to https://github.com/datapackages/datapackage-py/
