### ISSUE TITLE
Include command-line interface?

### ISSUE THREAD

**Issue by rlafuente** [okfn/datapackage-validate-py#7]
This lib is super useful, but we needed a CLI interface and this happened:

https://github.com/rlafuente/datapackage-validator

Maybe it makes sense to integrate this interface into your validate library?

**Comment by pwalsh** [comment]
Hey @rlafuente great! We use this in other CLIs, but did not add one here directly. Would be happy to integrate. Would you like to start a pull request with the CLI code?

**Comment by s-celles** [comment]
I've just send a PR about this.
I removed from @rlafuente code `click` to avoid to add too much dependencies (I also love `click`... but `argparse` is installed by default)

Some improvements are still necessary such as validating several files.

**Comment by pwalsh** [comment]
All our CLIs use Click, it is no problem to keep it, and in fact it is preferred.

**Comment by s-celles** [comment]
Ok fixed and squashed but CI is failling because of a missing `dev-requirements.txt` file

https://travis-ci.org/okfn/datapackage-validate-py/jobs/109053992

```
$ pip install -r dev-requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'dev-requirements.txt'
The command "pip install -r dev-requirements.txt" failed and exited with 1 during .
```

**Comment by rlafuente** [comment]
Wow, that was _fast_! Awesome that you improved my crude output statements, thanks.

**Comment by vitorbaptista** [comment]
That's a great suggestion, @rlafuente, and thanks for the PR, @scls19fr. This repository is deprecated now, though, and the development will happen in `datapackage-py` in the future. I've replicated this issue there https://github.com/datapackages/datapackage-py/issues/47
